### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by findthebug** [youngcut/kirby-map#6]
It looks like if you using the plugin in combination with a checkbox field (see categories), sometime you can't save the map anymore. 

Map: 1.0.3
Kirby: 3.5.0

<img width="974" alt="Bildschirmfoto 2021-10-19 um 14 57 52" src="https://user-images.githubusercontent.com/5121132/137913994-1f0a85b7-b456-46e8-9d2a-e1c36d8be929.png">

```
  name: Modul - Karte
  icon: 🗺
  fields:
    headline:
      label: Überschrift
      type: text
    txt:
      label: Text
      type: textarea
      buttons: false     
    categories:
      label: Legende
      type: checkboxes
      options:
        - value: 1
          text: Institution
        - value: 2
          text: Wohnen
        - value: 3
          text: Arbeiten
        - value: 4
          text: Tagesstruktur    
    mapdata:
      label: Karte
      type: blocks
      fieldsets:
          - maps
       ```
The solution is, to remove the categories e.g checkboxes from the blueprint.  Not sure checkboxes is the only filed or maybe other fields as well causing the issue.

**Comment by findthebug** [comment]
```    
categories:
      label: Legende
      type: checkboxes
      options:
        i: Institution
        w: Wohnen
        a: Arbeiten
        t: Tagesstruktur  
```

this will also work
